### ISSUE TITLE
Links to wallpaper no longer work

### ISSUE THREAD

**Issue by michihupf** [joepigott/dots#2]
In the [installation instructions](https://github.com/joepigott/dots/blob/main/install.md) the links to the wallpaper no longer work (time out). 

Is there still a way to get the wallpaper somewhere?

**Comment by joepigott** [comment]
The links still work for me, I will be updating the repository soon though. I may make a directory dedicated to all of my old wallpapers.

**Comment by joepigott** [comment]
I've added a wallpaper directory so there shouldn't be an issue now. If you need one in another resolution just let me know, I can re-render it for you.
