### ISSUE TITLE
Suggestion: Add HW Info to bar - Cyberpunk

### ISSUE THREAD

**Issue by fxrstor** [joepigott/dots#4]
Just a suggestion if you have time. 
Add memory usage (in MB) and CPU usage (in %) functionality to a bar. Plus while displaying volume, display the percentage of the volume too. For some reason, the volume thing is not being displayed in my arch. The icons are really small (systray icons are too large), is there any fix for it? Should I increase the font? 
![image](https://github.com/user-attachments/assets/474dc72e-6e15-4fb7-be69-f8a8e22b0f88)

**Comment by joepigott** [comment]
All of this probably depends on your own setup (display size, dpi, etc.), which I won't be able to make changes for or test in any way. It's fine for me, and that's really all this repository is; it's a starting point based on what I use for my workflow. It's expected that you'll probably need to make a few tweaks or add some features yourself. For the widgets you'd like, I'd suggest looking through the [awesomewm docs](https://awesomewm.org/apidoc/documentation/07-my-first-awesome.md.html). I think they have some examples that are similar to what you suggested
